export const MOCK_PRODUCTS = [
  { id: 1, name: "Premium Hoodie - Slate Grey", slug: "hoodie-grey", price: 89.99, category: "Apparel", stock: 15, description: "Our signature heavyweight hoodie, designed for comfort and durability. Features a brushed fleece interior and minimalist detailing.", imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop" },
  { id: 2, name: "Minimalist Leather Wallet", slug: "wallet-leather", price: 49.50, category: "Accessories", stock: 5, description: "A sleek, bifold wallet crafted from vegetable-tanned Italian leather. Holds 6 cards and cash without the bulk.", imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop" },
  { id: 3, name: "Ceramic Coffee Mug (Set of 2)", slug: "mug-ceramic", price: 29.00, category: "Home Goods", stock: 20, description: "A beautifully hand-glazed ceramic mug set with a comfortable, oversized handle. Perfect for your morning ritual.", imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=400&h=400&fit=crop" },
  { id: 4, name: "Travel Backpack - Utility Black", slug: "backpack-utility", price: 159.99, category: "Bags", stock: 8, description: "Water-resistant travel backpack with dedicated laptop sleeve and concealed pockets for security on the go.", imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop" },
  { id: 5, name: "The Essential T-Shirt", slug: "tshirt-essential", price: 25.00, category: "Apparel", stock: 30, description: "Soft, breathable cotton in a perfect fit.", imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop" },
  { id: 6, name: "Sleek Desk Lamp", slug: "lamp-desk", price: 79.99, category: "Home Goods", stock: 10, description: "Adjustable LED lamp with three brightness modes.", imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop" },
  { id: 7, name: "Wireless Bluetooth Headphones", slug: "headphones-bluetooth", price: 129.99, category: "Electronics", stock: 12, description: "Premium wireless headphones with noise cancellation and 30-hour battery life.", imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop" },
  { id: 8, name: "Smart Fitness Watch", slug: "watch-fitness", price: 199.99, category: "Electronics", stock: 7, description: "Track your workouts, heart rate, and sleep with this advanced fitness smartwatch.", imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop" },
];

export const MOCK_TESTIMONIALS = [
    { id: 1, text: "The quality is unmatched. My hoodie arrived quickly and feels like it will last for years!", author: "Sarah L.", rating: 5 },
    { id: 2, text: "Customer service was fantastic, and the wallet is exactly as described—minimal and high-end.", author: "Mark R.", rating: 5 },
    { id: 3, text: "Love the coffee mugs! They are the perfect size and look great in my kitchen.", author: "Jessica H.", rating: 4 },
];